Validate source files.

diff --git a/makedeb b/makedeb
--- a/makedeb
+++ b/makedeb
@@ -23,6 +23,7 @@
 declare retval
 declare missing_depends=()
 declare installed_depends=()
+declare source_files=()
 
 
 declare pkgname=""
@@ -31,8 +32,9 @@ declare pkgrel=""
 declare depends=()
 declare makedepends=()
 declare checkdepends=()
-declare source
-declare sources
+declare source=()
+declare sources=()
+declare sha1sums=()
 
 # GLOBALS
 
@@ -60,6 +62,7 @@ REMOVE_DEPENDS=0
 print1() {
     echo -e "${ANSI_GREEN}${ANSI_BOLD}==>${ANSI_RESET}${ANSI_BOLD} ${1}${ANSI_RESET}"
 }
+
 
 print2() {
     echo -e "  ${ANSI_BLUE}${ANSI_BOLD}->${ANSI_RESET}${ANSI_BOLD} ${1}${ANSI_RESET}"
@@ -292,13 +295,64 @@ retrieve_sources() {
         if [[ -f "${startdir}/${name}" ]]; then
             print2 "Found ${name}"
         else
-            print2 "Downloading $name"
-            curl --location --output "${startdir}/${name}" "$url"
+            print2 "Downloading ${name}"
+            if ! curl --location --output "${startdir}/${name}" "$url"; then
+                error "Failed to download '${name}' from ${url}"
+            fi
         fi
+        source_files+=("$name")
     done
 }
 
 
+validate_sources() {
+    local failed=0
+    if _validate_sources md5sum; then
+        failed=1
+    fi
+    if _validate_sources sha1sum; then
+        failed=1
+    fi
+    if _validate_sources sha256sum; then
+        failed=1
+    fi
+    if _validate_sources sha384sum; then
+        failed=1
+    fi
+    if _validate_sources sha512; then
+        failed=1
+    fi
+    if [[ $failed -gt 0 ]]; then
+        error "One or more files did not pass the validity check!"
+    fi
+}
+
+
+_validate_sources() {
+    local -n sums="${1}s"
+    if [[ ${#sums[@]} -gt 0 ]]; then
+        print1 "Validating source files with ${1}s..."
+        if [[ ${#sums[@]} -ne ${#source_files[@]} ]]; then
+            error "'${1}s' array not the same length as the 'source' array."
+        fi
+        local sum
+        local failed=0
+        for ((i=0;i<${#source_files[@]};++i)); do
+            if [[ ${sums[i]^^} != "SKIP" ]]; then
+                echo -en "  ${ANSI_BLUE}${ANSI_BOLD}->${ANSI_RESET} "
+                echo -en "${ANSI_BOLD}${source_files[i]} ... ${ANSI_RESET}"
+                sum=$(${1} "${startdir}/${source_files[i]}" | cut -d' ' -f1)
+                if [[ "$sum" == "${sums[i]}" ]]; then
+                    echo -e "${ANSI_BOLD}Passed${ANSI_RESET}"
+                else
+                    echo -e "${ANSI_RED}${ANSI_BOLD}FAILED${ANSI_RESET}"
+                    failed=1
+                fi
+            fi
+        done
+        return $failed
+    fi
+}
 
 
 
@@ -321,11 +375,7 @@ check_buildtime_depends
 check_checktime_depends
 install_missing_depends
 retrieve_sources
+validate_sources
 
 cleanup
 print_completion_message
-
-
-
-
-
